# Generated by Django 3.1 on 2020-12-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Active_a_pred',
            field=models.FloatField(default=100, verbose_name='active_a'),
        ),
        migrations.AddField(
            model_name='player',
            name='Active_b_pred',
            field=models.FloatField(default=100, verbose_name='active_b'),
        ),
    ]
