# Generated by Django 3.1 on 2020-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20201206_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Education',
            field=models.IntegerField(default=0, verbose_name='education'),
        ),
    ]
