# Generated by Django 3.1 on 2021-02-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20201207_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=200, verbose_name='name1')),
                ('Name2', models.CharField(max_length=200, verbose_name='name2')),
                ('Day', models.IntegerField(verbose_name='day')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.player')),
            ],
        ),
    ]
