# Generated by Django 3.1 on 2021-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('Name_eng', models.CharField(max_length=200, verbose_name='name_eng')),
            ],
        ),
    ]
