# Generated by Django 3.1 on 2021-02-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='Name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.active'),
        ),
    ]
