# Generated by Django 3.1 on 2021-02-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_auto_20210227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='Name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_a', to='Game.active'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='Name2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_b', to='Game.active'),
        ),
    ]
