# Generated by Django 3.1 on 2021-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
