# Generated by Django 3.1 on 2021-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Name',
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
