# Generated by Django 3.1 on 2021-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_auto_20210302_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
