# Generated by Django 3.1 on 2021-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_auto_20210513_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='ID',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Name',
            field=models.CharField(default=2, max_length=200, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
