# Generated by Django 3.1 on 2021-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_factor_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='ActA_increase',
            field=models.CharField(max_length=10, null=True, verbose_name='actAinc'),
        ),
        migrations.AddField(
            model_name='factor',
            name='ActB_increase',
            field=models.CharField(max_length=10, null=True, verbose_name='actBinc'),
        ),
    ]
