# Generated by Django 3.1 on 2021-05-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0014_player_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='ActA_increase',
            field=models.CharField(default='обрабатывается', max_length=10, null=True, verbose_name='actAinc'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='ActB_increase',
            field=models.CharField(default='обрабатывается', max_length=10, null=True, verbose_name='actBinc'),
        ),
    ]
