# Generated by Django 3.2.5 on 2021-09-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_auto_20210514_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='ActC_increase',
            field=models.CharField(default='обрабатывается', max_length=10, null=True, verbose_name='actCinc'),
        ),
        migrations.AddField(
            model_name='factor',
            name='Name3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_c', to='Game.active'),
        ),
        migrations.AddField(
            model_name='player',
            name='Active_c',
            field=models.FloatField(default=100, verbose_name='active_c'),
        ),
        migrations.AddField(
            model_name='player',
            name='Active_c_pred',
            field=models.FloatField(default=100, verbose_name='active_c'),
        ),
    ]
